[package]
name = "alterbot"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
config = { version = "0.15.25", default-features = false, features = ["toml"] }
poise = "0.6.2"
serde = { version = "1.0.229", features = ["derive"] }
serenity = "0.12.5"
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["chrono", "env-filter"] }
sea-orm = { version = "^2.0.0", features = ["runtime-tokio-rustls", "entity-registry", "schema-sync", "sqlx-postgres"] }
uuid = { version = "1.24.0", features = ["v4"] }
chrono = "0.4.45"
craftping = { version = "0.7.0", features = ["async-tokio"] }
serde_json = "1.0.151"
ferinth = "2.13.1"
reqwest.workspace = true
url = "2.5.8"
toml = "1.1.3"
futures = "0.3.33"
axum = "0.8.9"
notify = "8.2.0"
dashmap = "6.2.1"
awty = { git = "https://github.com/thatgurkangurk/are-we-there-yet", package = "are-we-there-yet-core", tag = "v0.7.1" }
quoter = { path = "../quoter" }
